In [3]:
import numpy as np 
from si.io.csv_file import read_csv

**1.1. Load the "iris.csv" using the appropriate method for this file type**

In [5]:
dataset = read_csv("/Users/inesglameira/Documents/GitHub/SIB/datasets/iris/iris.csv", sep=",", features=True, label=True)

print("X shape:", dataset.X.shape)
print("y shape:", dataset.y.shape)
print("features:", dataset.features)
print("label:", dataset.label)

X shape: (150, 4)
y shape: (150,)
features: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')
label: class


**1.2. Select the penultimate independent variable. What is the dimension of the resulting array?**

In [6]:
penultimate_feature = dataset.X[:, -2]
print("Shape:", penultimate_feature.shape)
penultimate_feature[:10]

Shape: (150,)


array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5])

**1.3.  Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable/feature?**

In [7]:
last_10 = dataset.X[-10:]
mean_last_10 = last_10.mean(axis=0)

print("Last 10 shape:", last_10.shape)
print("Mean of last 10 samples:", mean_last_10)

Last 10 shape: (10, 4)
Mean of last 10 samples: [6.45 3.03 5.33 2.17]


**1.4. Select all samples from the dataset with values less than or equal to 6 for all independent variables/features. How many samples do you obtain?**


In [9]:

mask = (dataset.X <= 6).all(axis=1)
selected = dataset.X[mask]

print("Number of samples:", selected.shape[0])
selected[:5]  # primeiros 5

Number of samples: 89


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

**1.5. Select all samples with a class/label different from 'Iris-setosa'. How many samples do you obtain?**

In [10]:
mask = dataset.y != "Iris-setosa"
selected = dataset.X[mask]

print("Number of samples:", selected.shape[0])
selected[:5]

Number of samples: 100


array([[7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5]])